# values.yaml
# Default values for Odoo - Configuration générique multi-tenant

replicaCount: 1

# Informations du client/projet
client:
  host: "argo2.mokatourisme.dev"  # URL d'accès
  name: "argo2"  # Nom du projet/client (utilisé pour nommer toutes les ressources)
  namespace: "odoo-argo2"  # Namespace dédié
  language: "fr_FR"  # Langue par défaut
  modules: "base"  # Modules à installer par défaut

image:
  repository_name: "ghcr.io/moka-tourisme/docker-moka"  # Image personnalisée avec wkhtmltopdf
  tag: "18-argo"
  pullPolicy: Always
  registrySecret: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "Um9tMTA4MTE6Z2hwX1pYR2lYV2NPV2RWZERFVG9kSW5BYm9abHd0d1NDTDM0bjV0WQ=="
        }
      }
    }

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

service:
  type: ClusterIP
  targetPort: 8069
  port: 8069

resources:
  limits:
    memory: 1024Mi
    cpu: 500m
  requests:
    cpu: 150m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}

# Configuration CloudNativePG
postgres:
  cluster:
    name: ""  # Auto-généré: {{ .Values.client.name }}-postgres
    instances: 2  # Nombre d'instances PostgreSQL
    storage:
      size: 20Gi
      storageClass: ""
  database:
    name: ""  # Auto-généré: {{ .Values.client.name }}
    owner: "odoo"  # Utilisateur propriétaire de la DB
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      cpu: 250m
      memory: 256Mi

# Configuration Odoo
odoo:
  adminPassword: "YWRtaW4xMjM="  # admin123 en base64
  # Probes de santé
  livenessProbe:
    initialDelaySeconds: 300
    periodSeconds: 30
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5

# Configuration Ingress
ingress:
  enabled: true
  className: "traefik"
  host: ""  # Auto-généré si vide: {{ .Values.client.host }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: ""  # Auto-généré: {{ .Values.client.name }}-tls-cert

# Stockage filestore Odoo
persistence:
  enabled: true
  size: 10Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce
