# Default values for Apm Ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository_name: odoo
  tag: 18.0
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: { }
  name:

podSecurityContext: { }

securityContext:
  runAsUser: 101

service:
  type: NodePort
  targetPort: 8069
  port: 8069

resources:
  limits:
    # cpu: 300m
    memory: 1024Mi
  requests:
    cpu: 150m
    memory: 512Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }

database:
  repository_name: postgres
  tag: 16.0
  pullPolicy: Always
  user: admin
  password: cm9vdA==  # base64 encodé
  name: odoo
  storage: 10Gi
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
