# Default values for Apm Ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository_name: odoo
  tag: 18.0
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: { }
  name:

podSecurityContext:
  fsGroup: 101
  runAsUser: 101
  runAsGroup: 101

securityContext:
  runAsUser: 101
  runAsGroup: 101
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false


service:
  type: ClusterIP  # Changé de NodePort vers ClusterIP pour l'ingress
  targetPort: 8069
  port: 8069
  # nodePort supprimé car on utilise l'ingress maintenant

resources:
  limits:
    # cpu: 300m
    memory: 1024Mi
  requests:
    cpu: 150m
    memory: 512Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }

database:
  host: localhost  # PostgreSQL sera dans le même pod
  user: admin
  password: cm9vdA==  # Votre mot de passe déjà encodé en base64
  name: odoo

# Nouvelles configurations
postgres:
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      cpu: 250m
      memory: 256Mi

ingress:
  enabled: true
  className: "nginx"  # Ajustez selon votre ingress controller
  host: "argo1.mokatourisme.dev"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Mettez true si vous voulez HTTPS
    # nginx.ingress.kubernetes.io/cert-manager-cluster-issuer: "letsencrypt-prod"  # Si vous utilisez cert-manager
  tls: [ ]
  # tls:
  #   - secretName: odoo-tls
  #     hosts:
  #       - argo1.mokatourisme.dev

persistence:
  enabled: true  # Mettez true pour la production
  size: 10Gi
  storageClass: ""

