# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.name }}-odoo
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.client.name }}-odoo
    client: {{ .Values.client.name }}
    component: odoo
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.client.name }}-odoo
      client: {{ .Values.client.name }}
      component: odoo
  template:
    metadata:
      labels:
        app: {{ .Values.client.name }}-odoo
        client: {{ .Values.client.name }}
        component: odoo
    spec:
      imagePullSecrets:
        - name: {{.Values.client.name}}-registry-secret
      containers:
        - name: odoo
          image: "{{ .Values.image.repository_name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 8069
              protocol: TCP
          env:
            # CloudNativePG - Connexion via le service du cluster
            - name: HOST
              value: {{ .Values.client.name }}-postgres-rw
            - name: PORT
              value: "5432"
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.client.name }}-postgres-app
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.client.name }}-postgres-app
                  key: password
            - name: DB_NAME
              value: {{ .Values.client.name }}
          volumeMounts:
            - name: filestore
              mountPath: /var/lib/odoo/filestore
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: filestore
          persistentVolumeClaim:
            claimName: {{ .Values.client.name }}-odoo-filestore  # ✅ Nom cohérent
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
