# templates/postgresql-cnpg.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-{{ .Values.client.name }}
  namespace: {{ .Values.client.namespace }}
spec:
  instances: {{ .Values.postgres.cluster.instances | default 3 }}
  bootstrap:
    initdb:
      database: {{ .Values.database.name }}
      owner: {{ .Values.database.user }}
      secret:
        name: {{ .Values.client.name }}-postgres-credentials
  storage:
    size: {{ .Values.postgres.cluster.storage.size }}
