# templates/postgresql-cnpg.yaml (version simplifiée)
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.client.name }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.postgres.cluster.instances | default 2 }}

  # ✅ Version PostgreSQL 16
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  # ✅ Bootstrap simplifié
  bootstrap:
    initdb:
      database: {{ .Values.client.name }}
      owner: odoo
      encoding: UTF8
      # ✅ Pas de locales spécifiques = utilise les defaults système
      secret:
        name: {{ .Values.client.name }}-postgres-superuser

  # Configuration du stockage
  storage:
    size: {{ .Values.postgres.cluster.storage.size | default "20Gi" }}
    {{- if .Values.postgres.cluster.storage.storageClass }}
    storageClass: {{ .Values.postgres.cluster.storage.storageClass }}
    {{- end }}

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "128MB"
      effective_cache_size: "512MB"

  resources:
    {{- toYaml .Values.postgres.resources | nindent 4 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.client.name }}-postgres-superuser
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ "postgres" | b64enc }}
  password: {{ "postgres123" | b64enc }}
