apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.client.name }}-secrets
  namespace: {{ .Values.client.namespace }}
type: Opaque
data:
  db-password: {{ .Values.database.password }}
  admin-password: {{ .Values.odoo.adminPassword }}
---
{{- if .Values.image.registrySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.client.name }}-registry-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.image.registrySecret | b64enc }}
{{- end }}
