# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.name }}-odoo
  namespace: {{ .Values.client.namespace }}
  labels:
    app: {{ .Values.client.name }}-odoo
    client: {{ .Values.client.name }}
    component: odoo
spec:
  type: "ClusterIP"
  ports:
    - port: 8069
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.client.name }}-odoo
    client: {{ .Values.client.name }}
    component: odoo