# Valeurs pour le client automobile
replicaCount: 1

client:
  name: "automobile"
  host: "automobile.duciel.cloud"
  namespace: "odoo-automobile"
  modules: "event,sale,crm"
  language: "fr_FR"

image:
  repository_name: "ghcr.io/moka-tourisme/docker-moka"  # Image personnalisée avec wkhtmltopdf
  tag: "18-argo"
  pullPolicy: Always
  registrySecret: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "Um9tMTA4MTE6Z2hwX1pYR2lYV2NPV2RWZURFVG9kSW5BYm9abHd0d1NDTDM0bjV0WQ=="
        }
      }
    }

database:
  host: postgresql-service
  user: admin
  password: cm9vdA==
  name: "automobile.duciel.cloud"

odoo:
  adminPassword: "YWRtaW4xMjM="

ingress:
  enabled: true
  className: "traefik"
  host: "automobile.duciel.cloud"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "automobile--letsencrypt-prod"
  tls:
    - secretName: odoo-tls-cert
      hosts:
        - "automobile.duciel.cloud"

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""

# Configuration PostgreSQL CloudNativePG avec version 16
postgres:
  cluster:
    instances: 2
    storage:
      size: 20Gi
      storageClass: ""
    # ✅ Version PostgreSQL 16
    imageName: "ghcr.io/cloudnative-pg/postgresql:16"
  resources:
    limits:
      memory: 1Gi
      cpu: 1000m
    requests:
      cpu: 500m
      memory: 512Mi

# ✅ Configuration Odoo avec probes corrigées
livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

