# environments/clients/automobile-values.yaml
client:
  host: "automobile.mokatourisme.dev"
  name: "automobile"
  namespace: "odoo-automobile"
  language: "fr_FR"
  modules: "base,sale,purchase,stock"

# Structure correcte des probes
livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 30
  timeoutSeconds: 5

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

# Structure correcte de l'ingress
ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - secretName: automobile-tls-cert
      hosts:
        - "automobile.mokatourisme.dev"

postgres:
  cluster:
    instances: 2
    storage:
      size: 30Gi
  resources:
    limits:
      memory: 1Gi
      cpu: 1000m
    requests:
      cpu: 500m
      memory: 512Mi

resources:
  limits:
    memory: 2Gi
    cpu: 1000m
  requests:
    cpu: 300m
    memory: 1Gi
