kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "odoo.name" . }}
  namespace: {{ .Values.client.namespace}}  # 🎯 Ajout du namespace
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
data:
  HOST: {{ .Values.database.host | quote }}
  USER: {{ .Values.database.user | quote }}
  # Ajout de la config Odoo
  odoo.conf: |
    [options]
    addons_path = /mnt/extra-addons
    data_dir = /var/lib/odoo

    db_host = {{ .Values.database.host }}
    db_port = 5432
    db_user = {{ .Values.database.user }}
    db_name = {{ .Values.database.name }}

    xmlrpc_port = 8069
    log_level = info
    list_db = False