apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: {{ .Values.client.namespace | default .Release.Namespace }}
data:
  odoo.conf: |
    [options]
    # Base de données
    db_host = {{ .Values.database.host }}
    db_port = 5432
    db_user = {{ .Values.database.user }}
    db_password = {{ .Values.database.password | b64dec }}

    # Filtrage de base de données (sécurité importante)
    dbfilter = {{ .Values.database.dbfilter }}

    # Serveur
    http_port = 8069
    data_dir = /var/lib/odoo

    # Admin
    admin_passwd = {{ .Values.odoo.adminPassword | b64dec }}

    # Autres
    addons_path = /usr/lib/python3/dist-packages/odoo/addons
    list_db = False
    log_level = info
