kind: ConfigMap
apiVersion: v1
metadata:
  name: odoo-config  # 🎯 Nom plus explicite
  namespace: {{ .Values.client.namespace }}       # 🎯 OBLIGATOIRE
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
data:
  # Variables d'environnement
  HOST: {{ .Values.database.host | quote }}
  USER: {{ .Values.database.user | quote }}

  # Configuration Odoo complète
  odoo.conf: |
    [options]
    addons_path = /mnt/extra-addons
    data_dir = /var/lib/odoo

    # Base de données
    db_host = {{ .Values.database.host }}
    db_port = 5432
    db_user = {{ .Values.database.user }}
    db_name = {{ .Values.database.name }}

    # Serveur web
    xmlrpc_port = 8069
    xmlrpc_interface = 0.0.0.0

    # Logs et sécurité
    log_level = info
    list_db = False

    # Performance
    workers = 2
    max_cron_threads = 1
