apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: {{ .Values.client.namespace | default .Release.Namespace }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
data:
  HOST: {{ .Values.database.host | quote }}
  USER: {{ .Values.database.user | quote }}

  odoo.conf: |
    [options]
    addons_path = /mnt/extra-addons
    data_dir = /var/lib/odoo

    # Base de données
    db_host = {{ .Values.database.host }}
    db_port = 5432
    db_user = {{ .Values.database.user }}
    db_name = {{ .Values.database.name }}
    db_password = odoo123

    # Serveur web
    proxy_mode = True
    xmlrpc_port = 8069
    xmlrpc_interface = 0.0.0.0

    # Logs et sécurité
    log_level = info
    list_db = True

    # Performance
    workers = 2
    max_cron_threads = 1
