apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-{{ .Values.client.name }}
  namespace: {{ .Values.client.namespace | default .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      client: {{ .Values.client.name }}
  template:
    metadata:
      labels:
        app: postgresql
        client: {{ .Values.client.name }}
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_DB
          value: {{ .Values.database.name }}
        - name: POSTGRES_USER
          value: {{ .Values.database.user }}
        - name: POSTGRES_PASSWORD
          value: odoo123
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
{{ toYaml .Values.postgres.resources | indent 10 }}
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc-{{ .Values.client.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: {{ .Values.client.namespace | default .Release.Namespace }}
spec:
  selector:
    app: postgresql
    client: {{ .Values.client.name }}
  ports:
  - port: 5432
    targetPort: 5432
