apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo.name" . }}-postgresql
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "odoo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
