apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "odoo.name" . }}-postgresql-pvc
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage | default "10Gi" }}
