apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.client.name }}-secrets
  namespace: {{ .Values.client.namespace | default .Release.Namespace }}
type: Opaque
data:
  db-password: {{ .Values.database.password }}
  admin-password: {{ .Values.odoo.adminPassword }}
